package fps.subskipper.recognitionManualParser;

import static fps.subskipper.util.Constants.SHIP_DATA_READER_RESOURCES_PATH;
import static fps.subskipper.util.Constants.UBOOT_ENTITIES_PATH;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;

import fps.subskipper.core.Ships;
import fps.subskipper.recognitionManualParser.writers.ParseRecognitionManualLong;
import fps.subskipper.recognitionManualParser.writers.ParseRecognitionManualShort;
import ship.data.reader.IShipDataReader;
import ship.data.reader.uboat.ReadUboatShipData;

public class RecognitionManualUbootImpl implements RecognitionManualMainInterface {

  @Override
  public Ships loadShipsToMemory(File dataPath) throws IOException {
    IShipDataReader ubootDataReader = new ReadUboatShipData();
    return ubootDataReader.readShipsFromData(dataPath);
  }

  @Override
  public Ships loadShipsToMemory() throws IOException {
    IShipDataReader ubootDataReader = new ReadUboatShipData();
    return ubootDataReader.readShipsFromData(new File(UBOOT_ENTITIES_PATH));
  }

  @Override
  public void publishRecognitionManualShort(Ships shipList, String filename, boolean isImperial, boolean isGenerateAOBTable)
      throws FileNotFoundException {
        ParseRecognitionManualShort parseShortManual = new ParseRecognitionManualShort();
        parseShortManual.writeRecogSHTML(shipList, filename, isImperial, isGenerateAOBTable);
  }

  @Override
  public void publishRecognitionManualLong(Ships shipList, String filename, boolean isImperial) throws FileNotFoundException {
      //TODO: filename should be autogenerated, path should be set by user.
        ParseRecognitionManualLong parseLongManual = new ParseRecognitionManualLong();
        parseLongManual.writeRecogLHTML(shipList, filename, isImperial);
  }

}
