package fps.subskipper.recognitionManualParser;

import fps.subskipper.core.Ships;
import fps.subskipper.recognitionManualParser.writers.ParseRecognitionManualLong;
import fps.subskipper.recognitionManualParser.writers.ParseRecognitionManualShort;
import ship.data.reader.IShipDataReader;
import ship.data.reader.sh4.ReadShipsFromSh4DataImpl;

import java.io.File;
import java.io.FileNotFoundException;

import static fps.subskipper.util.Constants.SCAF_ROOT_PATH;

public class RecognitionManualMainImpl implements RecognitionManualMainInterface {

    @Override
    public Ships loadShipsToMemory(File dataPath) {
        IShipDataReader shipDataReader = new ReadShipsFromSh4DataImpl();
        return shipDataReader.readShipsFromData(dataPath);
    }

    @Override
    public Ships loadShipsToMemory() {
      return loadShipsToMemory(new File(SCAF_ROOT_PATH));
    }

    @Override
    public void publishRecognitionManualShort(Ships shipList, String filename, boolean isImperial, boolean aobTable) throws FileNotFoundException {

        //TODO: filename should be autogenerated, path should be set by user.

        ParseRecognitionManualShort parseShortManual = new ParseRecognitionManualShort();
        parseShortManual.writeRecogSHTML(shipList, filename, isImperial, aobTable);
    }

    @Override
    public void publishRecognitionManualLong(Ships shipList, String filename, boolean isImperial) throws FileNotFoundException {
        //TODO: filename should be autogenerated, path should be set by user.
        ParseRecognitionManualLong parseLongManual = new ParseRecognitionManualLong();
        parseLongManual.writeRecogLHTML(shipList, filename, isImperial);
    }
}
